version: "3.8"
services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/volsor/frontend-apps/call_back

    volumes:
      - ./:/call_back
    ports:
      - 3000:3000
    container_name: call_back
